// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using PhotosOfUs.Model.Models;
using System;

namespace PhotosOfUs.Model.Migrations
{
    [DbContext(typeof(PhotosOfUsContext))]
    [Migration("20180205131106_CardTable")]
    partial class CardTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PhotosOfUs.Model.Models.Card", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime");

                    b.Property<int>("PhotographerId");

                    b.HasKey("Id");

                    b.HasIndex("PhotographerId");

                    b.ToTable("Card");
                });

          

       
            modelBuilder.Entity("PhotosOfUs.Model.Models.Card", b =>
                {
                    b.HasOne("PhotosOfUs.Model.Models.User", "Photographer")
                        .WithMany("Card")
                        .HasForeignKey("PhotographerId")
                        .HasConstraintName("FK_Card_Photographer")
                        .OnDelete(DeleteBehavior.Cascade);
                });

         
#pragma warning restore 612, 618
        }
    }
}
